config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :posts
  
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date, presence: true
    validates :end_date, presence: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, presence: true, length: { maximum: 20 }
    validates :start_datetime, presence: true
    validates :end_datetime, presence: true
    validates :memo, length: { maximum: 500 } 
    validate :end_datetime_after_start_datetime
    
  
    private
  
    def end_datetime_after_start_datetime
      if end_datetime.present? && start_datetime.present? && end_datetime < start_datetime
        errors.add(:end_datetime, "must be after the start date")
      end
    end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :title, presence: true
    validates :start_time, presence: true
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
        helper ApplicationHelper
 end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
      @events = Event.all
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @post = Post.find_by(id: params[:id])
    @today = Date.today
    @total_posts = @posts.count
  end

  def create
    @post = Post.new(post_params)
    # redirect_to '/posts'
    if @post.save
      flash[:notice] = "新規投稿に成功しました"
      redirect_to posts_path
    else
      flash[:notice] = "新規投稿に失敗しました"
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:content, :start_datetime, :end_datetime, :is_all_day, :memo)
  end
  # content: params[:content]
  def new
    @post = Post.new
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def show
    # @post = Post.find(params[:id])
    # @id = params[:id]
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿の編集に成功しました"
      redirect_to posts_path
    else
      flash[:notice] = "投稿の編集に失敗しました"
      render :edit
    end
  end

  # def update
  #   @post = Post.new(post_params)
  #   @post.content = params[:content]
  #   if @post.save
  #     redirect_to '/posts'
  #   else
  #     redirect_to("/posts/#{@post.id}/edit")
  #   end
  # end

  #   @post.save
  #   redirect_to '/posts'
  # end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    # redirect_to("/posts/index")
    redirect_to '/posts'
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:notice] = 'スケジュールが作成されました。'
      redirect_to @schedule
    else
      flash[:alert] = 'スケジュールの作成に失敗しました。'
      render :new
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:title, :start_date, :end_date, :content)
  end
end

app/helpers/application_helper.rb
# app/helpers/application_helper.rb
  module ApplicationHelper
    # include SimpleCalendar::CalendarHelper
  end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>  
  
  <body>
    <header>
      <div class="header-logo">
       <p>スケジュール管理アプリ</p>
      </div>
    </header> 

    <% if flash[:notice] %>
      <div class="flash">
        <%=  flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">予定を編集してください</h1>

    <%= form_with(model: @post, local: true) do |f| %>
      <div class="form-body">
        <div class="form-group">
          <%= f.label :content, "タイトル", class: 'control-label' %>
          <%= f.text_area :content, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :start_datetime, "開始日", class: 'control-label' %>
          <%= f.date_field :start_datetime, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :end_datetime, "終了日", class: 'control-label' %>
          <%= f.date_field :end_datetime, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :is_all_day, "終日の場合はチェックを入れます", class: 'control-label' %>
          <%= f.check_box :is_all_day, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :memo, "スケジュールメモ", class: 'control-label' %>
          <%= f.text_area :memo, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= link_to 'キャンセル', posts_path, class: 'btn btn-secondary' %>
          <%= f.submit "送信", class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>

app/views/posts/index.html.erb
<div class="header-main">
  <p class="header-menus">予定一覧</p>
  <p class="header-menus"><%= link_to "新規追加", :new_post %></p>
</div>

<table class="table1">
  <tr>
    <th>id</th>
    <th>タイトル</th>
    <th>開始日</th>
    <th>終了日</th>
    <th>終日</th>
    <th>更新日時</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

 <tbody>
   <% @posts.each do |post|%>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.content %></td> 
      <td><%= post.start_datetime.present? ? post.start_datetime.strftime('%Y-%m-%d') : '未設定' %></td>
      <td><%= post.end_datetime.present? ? post.end_datetime.strftime('%Y-%m-%d') : '未設定' %></td>
      <td class="large-circle"><%= post.is_all_day ? '○' : '' %></td>
      <td><%= post.updated_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M') %></td>
      <td><%= link_to "詳細", post_path(post) %></td>
      <td><%= link_to "編集", edit_post_path(post) %></td>
      <td><%= link_to "削除", post_path(post), method: :delete, data: { confirm: "予定を削除しますか？" } %></td> 
    </tr>
   <% end %>
 </tbody>
</table>

<footer>
  <p>予定合計 <%= @total_posts %>件</p>
  <p class="footer1">本日の日付 <%= @today.strftime('%Y/%m/%d') %></p>
</footer>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">予定の新規追加</h1>

    <%= form_with(model: @post, local: true) do |f| %>
      <div class="form-body">
        <div class="form-group">
          <%= f.label :content, "タイトル", class: 'control-label' %>
          <%= f.text_area :content, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :start_datetime, "開始日", class: 'control-label' %>
          <%= f.date_field :start_datetime, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :end_datetime, "終了日", class: 'control-label' %>
          <%= f.date_field :end_datetime, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :is_all_day, "終日の場合はチェックを入れます", class: 'control-label' %>
          <%= f.check_box :is_all_day, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :memo, "スケジュールメモ", class: 'control-label' %>
          <%= f.text_area :memo, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= link_to 'キャンセル', posts_path, class: 'btn btn-secondary' %>
          <%= f.submit "送信", class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>

app/views/posts/show.html.erb
<div class="posts-show-item">
    <%= link_to("← 一覧に戻る", posts_path) %>
</div>

<div class="post-wrapper">
  <p class="post-content"><%= @post.content %></p>
  <div class="post-menus">
    <%= link_to("編集", edit_post_path(@post)) %> 
  </div>
</div>

<div class="post-details">
  <div class="post-detail">
    <span class="label">開始日:</span>
    <span class="value"><%= @post.start_datetime.strftime('%Y/%m/%d') %></span>
  </div>
  <div class="post-detail">
    <span class="label">終了日:</span>
    <span class="value"><%= @post.end_datetime.strftime('%Y/%m/%d') %></span>
  </div>
  <div class="post-detail">
    <span class="label">終日:</span>
    <span class="value"><%= @post.is_all_day ? '○' : '' %></span>
  </div>
  <div class="post-detail">
    <span class="label">スケジュールメモ:</span>
    <span class="value"><%= @post.memo %></span>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="main schedules-new">
  <div class="container">
    <h1 class="form-heading">新規スケジュール</h1>
    
    <%= form_with(model: @schedule, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :title, 'タイトル' %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.label :start_date, '開始日' %>
        <%= form.text_field :start_date, class: 'form-control', id: 'start_date' %>
      </div>
      
      <div class="form-group">
        <%= form.label :end_date, '終了日' %>
        <%= form.text_field :end_date, class: 'form-control', id: 'end_date' %>
      </div>
      
      <div class="form-group">
        <%= form.label :content, 'スケジュールメモ' %>
        <%= form.text_area :content, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= form.submit '作成', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></time>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%# <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %> %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <%# <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %> %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>